version: '3.9'

services:

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend-products:
    build: ./backend/products
    container_name: backend-products
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
    networks:
      - app-network

  backend-categories:
    build: ./backend/categories
    container_name: backend-categories
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend-products
      - backend-categories
    networks:
      - app-network

volumes:
  mysql-data:
  
networks:
  app-network:
