version: '3.9'

services:

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-network

  backend-products:
    image: gabrielmt2004/backend-products:v1
    container_name: backend-products
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      PORT: 8080
      DB_HOST: mysql-db
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: admin123
    networks:
      - spring-network

  backend-categories:
    image: gabrielmt2004/backend-categories:v1
    container_name: backend-categories
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      PORT: 8080
      DB_HOST: mysql-db
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: admin123
    networks:
      - spring-network

  frontend:
    image: gabrielmt2004/frontend:v1
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend-products
      - backend-categories
    networks:
      - spring-network

volumes:
  mysql-data:

networks:
  spring-network:
    driver: bridge
