version: '3.9'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: gestion
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  products-service:
    build: ./backend/products
    container_name: spring-products
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=mysql-db
    networks:
      - backend

  categories-service:
    build: ./backend/categories
    container_name: spring-categories
    depends_on:
      - db
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=mysql-db
    networks:
      - backend

  frontend:
    build: ./frontend
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - products-service
      - categories-service
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
