services:
  - type: web
    name: angular-frontend
    env: docker
    plan: free
    region: oregon
    rootDir: frontend
    dockerfilePath: frontend/Dockerfile

  - type: web
    name: products-api
    env: docker
    plan: free
    region: oregon
    rootDir: backend/products
    dockerfilePath: backend/products/Dockerfile
    envVars:
      - key: PORT
        value: 8081
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://<HOST_EXTERNO>:3306/<DB>?sslMode=REQUIRED
      - key: SPRING_DATASOURCE_USERNAME
        value: <USER>
      - key: SPRING_DATASOURCE_PASSWORD
        value: <PASS>
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.MySQLDialect

  - type: web
    name: categories-api
    env: docker
    plan: free
    region: oregon
    rootDir: backend/categories
    dockerfilePath: backend/categories/Dockerfile
    envVars:
      - key: PORT
        value: 8082
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://<HOST_EXTERNO>:3306/<DB>?sslMode=REQUIRED
      - key: SPRING_DATASOURCE_USERNAME
        value: <USER>
      - key: SPRING_DATASOURCE_PASSWORD
        value: <PASS>
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.MySQLDialect
